version: 1.0.{build}
branches:
  only:
  - develop
skip_tags: true
image: Visual Studio 2017
environment:
    NUGET_SOURCE: https://ci.appveyor.com/nuget/07101994-46vpdv1so3tq
    NUGET_APIKEY:
      secure: iR2nxYunwR8NlbHe5TRd0h2CETPfs9QPf6ibViJkjq8=
configuration: Release
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
  - ps: xcopy /s "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\*.*" "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\"
  - ps: .\build.ps1 -verbosity Minimal
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))